# docker-compose -f docker-compose.db.yml up -d
services:
  earlybird-redis:
    image: redis:latest
    container_name: earlybird-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - earlybird-redis_data:/data
    networks:
      - earlybird_network
    restart: always
    platform: linux/amd64

  earlybird-user-postgres:
    image: postgis/postgis:latest
    container_name: earlybird-user-postgres
    restart: always
    platform: linux/amd64
    ports:
      - "${POSTGRES_USER_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - earlybird_user_postgres_data:/var/lib/postgresql/data
    networks:
      - earlybird_network

  earlybird-concert-postgres:
    image: postgis/postgis:latest
    container_name: earlybird-concert-postgres
    restart: always
    platform: linux/amd64
    ports:
      - "${POSTGRES_CONCERT_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - earlybird_concert_postgres_data:/var/lib/postgresql/data
    networks:
      - earlybird_network

  earlybird-admin-postgres:
    image: postgis/postgis:latest
    container_name: earlybird-admin-postgres
    restart: always
    platform: linux/amd64
    ports:
      - "${POSTGRES_ADMIN_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - earlybird_admin_postgres_data:/var/lib/postgresql/data
    networks:
      - earlybird_network

  earlybird-coupon-postgres:
    image: postgis/postgis:latest
    container_name: earlybird-coupon-postgres
    restart: always
    platform: linux/amd64
    ports:
      - "${POSTGRES_COUPON_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - earlybird_coupon_postgres_data:/var/lib/postgresql/data
    networks:
      - earlybird_network

  earlybird-reservation-postgres:
    image: postgis/postgis:latest
    container_name: earlybird-reservation-postgres
    restart: always
    platform: linux/amd64
    ports:
      - "${POSTGRES_RESERVATION_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - earlybird_reservation_postgres_data:/var/lib/postgresql/data
    networks:
      - earlybird_network

  earlybird-payment-postgres:
    image: postgis/postgis:latest
    container_name: earlybird-payment-postgres
    restart: always
    platform: linux/amd64
    ports:
      - "${POSTGRES_PAYMENT_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - earlybird_payment_postgres_data:/var/lib/postgresql/data
    networks:
      - earlybird_network

  earlybird-venue-postgres:
    image: postgis/postgis:latest
    container_name: earlybird-venue-postgres
    restart: always
    platform: linux/amd64
    ports:
      - "${POSTGRES_VENUE_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - earlybird_venue_postgres_data:/var/lib/postgresql/data
    networks:
      - earlybird_network

  earlybird-alarm-postgres:
    image: postgis/postgis:latest
    container_name: earlybird-alarm-postgres
    restart: always
    platform: linux/amd64
    ports:
      - "${POSTGRES_ALARM_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - earlybird_alarm_postgres_data:/var/lib/postgresql/data
    networks:
      - earlybird_network

volumes:
  earlybird_user_postgres_data:
  earlybird_concert_postgres_data:
  earlybird_admin_postgres_data:
  earlybird_coupon_postgres_data:
  earlybird_reservation_postgres_data:
  earlybird_payment_postgres_data:
  earlybird_venue_postgres_data:
  earlybird_alarm_postgres_data:
  earlybird-redis_data:
networks:
  earlybird_network:
    driver: bridge