version: '3.8'

services:
  earlybird-grafana:
    image: grafana/grafana
    container_name: earlybird-grafana
    networks:
      - earlybird_network
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - earlybird-prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    restart: always

volumes:
  grafana_data:

networks:
  earlybird_network:
    driver: bridge