server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://earlybird-loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: local_logs
    static_configs:
      - targets:
          - localhost # 로그를 수집할 곳
        labels:
          job: varlogs
          __path__: /mnt/logs/*.log