services:
  eureka-service:
    image: ebt-registry.kr.ncr.ntruss.com/server:loadtest
    platform: linux/amd64
    environment:
      - SPRING_PROFILES_ACTIVE=loadtest
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    restart: on-failure:3