spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic

  jackson:
    property-naming-strategy: SNAKE_CASE

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:18080}/eureka
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30



server:
  port: ${AUTH_SERVER_PORT:18082}
  tomcat:
    mbeanregistry:
      enabled: true


jwt:
  secret: ${AUTH_JWT_SECRET}
  access:
    exp: ${AUTH_JWT_ACCESS_EXP}

management:
  endpoints:
    jmx:
      exposure:
        include: health,info,prometheus
    web:
      exposure:
        include: refresh,health,beans,busrefresh,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        all: true
    enable:
      jvm: true
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans"
  tracing:
    sampling:
      probability: ${ZIPKIN_SAMPLING_PROBABILITY:1.0}
  prometheus:
    metrics:
      export:
        enabled: true