spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:18080}/eureka


server:
  port: ${AUTH_SERVER_PORT:18082}


jwt:
  secret: ${AUTH_JWT_SECRET}
  access:
    exp: ${AUTH_JWT_ACCESS_EXP}
  refresh:
    exp: ${AUTH_JWT_REFRESH_EXP}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true


resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
    instances:
      shboard-circuit-breaker:
        base-config: default