spring:
  config:
    import: optional:file:.env[.properties]

  datasource-payment:
    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
    unique-resource-name: paymentDataSource
    max-pool-size: 10
    min-pool-size: 5
    xa-properties:
      serverName: ${POSTGRES_HOST:localhost}
      portNumber: ${POSTGRES_PAYMENT_PORT:5432}
      databaseName: ${POSTGRES_DB}
      user: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:postgres}

  datasource-admin:
    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
    unique-resource-name: adminDataSource
    max-pool-size: 10
    min-pool-size: 5
    xa-properties:
      serverName: ${POSTGRES_HOST:localhost}
      portNumber: ${POSTGRES_ADMIN_PORT:5432}
      databaseName: ${POSTGRES_DB}
      user: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:postgres}

  datasource-concert:
    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
    unique-resource-name: concertDataSource
    max-pool-size: 10
    min-pool-size: 5
    xa-properties:
      serverName: ${POSTGRES_HOST:localhost}
      portNumber: ${POSTGRES_CONCERT_PORT:5432}
      databaseName: ${POSTGRES_DB}
      user: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:postgres}

  datasource-coupon:
    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
    unique-resource-name: couponDataSource
    max-pool-size: 10
    min-pool-size: 5
    xa-properties:
      serverName: ${POSTGRES_HOST:localhost}
      portNumber: ${POSTGRES_COUPON_PORT:5432}
      databaseName: ${POSTGRES_DB}
      user: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:postgres}

  datasource-reservation:
    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
    unique-resource-name: reservationDataSource
    max-pool-size: 10
    min-pool-size: 5
    xa-properties:
      serverName: ${POSTGRES_HOST:localhost}
      portNumber: ${POSTGRES_RESERVATION_PORT:5432}
      databaseName: ${POSTGRES_DB}
      user: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:postgres}

  datasource-venue:
    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
    unique-resource-name: venueDataSource
    max-pool-size: 10
    min-pool-size: 5
    xa-properties:
      serverName: ${POSTGRES_HOST:localhost}
      portNumber: ${POSTGRES_VENUE_PORT:5432}
      databaseName: ${POSTGRES_DB}
      user: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:postgres}


