spring:
  config:
    import:
      - classpath:application-source-db.yml

  application:
    name: batch
    jpa:
      database: postgresql
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:/org/springframework/batch/core/schema-postgresql.sql
    job:
      name: comparisonJob
      enabled: false

  datasource-meta:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/metadata
    username: postgres
    password: postgres

  datasource-sink:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/data-db1
    username: postgres
    password: postgres

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

logging:
  level:
    org.springframework.batch.core.launch.support.SimpleJobOperator: ERROR
    org.springframework.batch.core.job.SimpleStepHandler: ERROR
server:
  port: 18091

management:
  endpoints:
    web:
      exposure:
        include: health, info, batch-job