services:
  reservation-service:
    image: ebt-registry.kr.ncr.ntruss.com/reservation:260318-454ad14
    container_name: reservation
    platform: linux/amd64
    environment:
      - SPRING_PROFILES_ACTIVE=loadtest
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_HOST=${POSTGRES_RESERVATION_HOST}
      - POSTGRES_RESERVATION_PORT=${POSTGRES_RESERVATION_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_RESERVATION_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - RESERVATION_IP_ADDRESS=${RESERVATION_IP_ADDRESS}
      - RESERVATION_SERVER_PORT=${RESERVATION_SERVER_PORT}
    ports:
      - "${RESERVATION_SERVER_PORT}:${RESERVATION_SERVER_PORT}"
    restart: on-failure:3

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    profiles: [ "loadtest" ]
    network_mode: host
    pid: host
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    restart: always